apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system: bootstrappers
      - system: nodes
      rolearn: arn:aws:iam::529088271493:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-SeWcQfLICvfC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: | # add user (Krishna, to map the IAM user Krishna into EKS)
  - groups:
      - default-trainee
    userarn: arn:aws:iam::529088271493:user/Krishna
    username: Krishna
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-12T03:11:32Z"
  name: aws-auth
  namespace: kube-system
  uid: d972cc24-07a9-4e49-b7a6-ef40196ace25
